apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-2910
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-2910 
  name: dot-2910
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot-2910
    weight: 100 
